### PR TITLE
attempt to address 'pointer' cursor issue raised by Montana on twitter

### PR DESCRIPTION
**Pull request by ryoe**
This is an attempt to address the concern raised by @calcnerd256 on [twitter](https://twitter.com/calcnerd256/status/489842961287364608) regarding the 'pointer' cursor when js is disabled. 

This PR will make the cursor pointer only appear when js is enabled, but makes no attempt to display the content that would be revealed when clicked with js enabled. Perhaps this PR can generate some discussion about how best to reveal the talk descriptions when js is not enabled.

### CODE REVIEW

**Comment by the-simian** [comment]
I just read over the code, and it looks pretty straightforward. I'll try to run it locally tommorrow and inspect it visually (as one must do with css).

Thank you very much for helping :) You rock.

**Comment by vlucas** [comment]
Thanks for the updates,  but the main styles are in `main.sass`, and the `main.css` is generated from that. So these changes will be obliterated on the next update. We'll have to get these changes in the main SASS file so we don't lose them.

**Comment by ryoe** [comment]
Doh! Thanks @vlucas. I won't be able to look at that until tonight.

**Comment by the-simian** [comment]
was fixed in a previous feature, closing.

**Pull request closed without merging**
